// Mode 3 데모 문구 사전 — 설계 2026-09-24-mode3-demo-ux-design.md §3. 전역 스크립트(빌드 없음).
// 규칙: verdicts.*.ko 는 tests/test_mode3_browser.mjs 의 needle 과 글자 그대로 같아야 한다(tests/test_mode3_demo_strings.js 가 검사).
// reasons.*.{cause,action} 은 docs/MODE3_DEMO.md 사유 표와 소스의 실제 발생 조건을 보고 쓴다 — 추측 금지.
window.DemoStrings = {
  langs: ['ko', 'en'],
  ui: {
    // 안내 바·토글
    bar_next: { ko: '다음: {where}에서 {what}', en: 'Next: {what} on {where}' },
    bar_other_window: { ko: '다른 창에서 진행', en: 'In another window' },
    toggle_lang: { ko: 'EN', en: '한국어' },
    toggle_expert: { ko: '전문가 보기', en: 'Expert view' },
    details: { ko: '자세히', en: 'Details' },
    working: { ko: '처리 중…', en: 'Working…' },
    error_title: { ko: '요청이 실패했습니다', en: 'The request failed' },
    proving: { ko: '영지식 증명 생성 중(약 1초)…', en: 'Generating zero-knowledge proof (~1 s)…' },
    go_wallet: { ko: '지갑 열기', en: 'Open wallet' }, go_rp: { ko: '서비스 열기', en: 'Open service' },
    go_admin: { ko: '신원 기관 관리자 열기', en: 'Open authority admin' }, go_account: { ko: '내 계정 페이지 열기', en: 'Open my account page' },
    where_wallet: { ko: '지갑', en: 'the wallet' }, where_rp: { ko: '서비스', en: 'the service' }, where_admin: { ko: '신원 기관 관리자', en: 'the authority admin' }, where_account: { ko: '내 계정 페이지', en: 'my account page' },
    confirm_revoke: { ko: '되돌릴 수 없습니다. 폐기할까요?', en: 'This cannot be undone. Revoke?' },
    confirm_publish: { ko: '폐기 목록을 체인에 게시합니다. 계속할까요?', en: 'Publish the revocation list on-chain. Continue?' },
    confirm_reset: { ko: 'Snap 의 등록 비밀과 동의 기록을 지웁니다. 계속할까요?', en: 'Erase the Snap’s registration secrets and consents. Continue?' },
    // 페이지 제목·카드 제목·설명 — T2~T4 가 쓴다(키 이름 = 페이지_카드_역할)
    wallet_title: { ko: 'Mode 3 지갑', en: 'Mode 3 Wallet' },
    wallet_identity_title: { ko: '내 신원', en: 'My identity' },
    wallet_identity_desc: { ko: '신원 기관에 한 번 등록합니다. 속성은 기관이 관리하고 지갑은 읽기만 합니다.', en: 'Register once with the identity authority. Attributes are managed by the authority; the wallet only reads them.' },
    wallet_sessions_title: { ko: '로그인 세션', en: 'Login sessions' },
    wallet_sessions_desc: { ko: '서비스마다 다른 주소로 로그인합니다. 세션 하나만 끝낼 수도 있습니다.', en: 'You log in with a different address per service. A single session can be ended on its own.' },
    wallet_tx_title: { ko: '트랜잭션 보내기', en: 'Send a transaction' },
    wallet_tx_desc: { ko: '이 서비스 전용 주소에서 보냅니다. 필요하면 속성 조건만 골라 공개합니다.', en: 'Sent from your service-specific address. Optionally reveal only chosen attribute conditions.' },
    wallet_snap_title: { ko: 'MetaMask · Snap', en: 'MetaMask · Snap' },
    wallet_snap_desc: { ko: '비밀은 Snap 안에 있습니다. 이 페이지는 동의만 받습니다.', en: 'Secrets live inside the Snap. This page only collects consent.' },
    wallet_auth_title: { ko: '로그인 승인', en: 'Approve login' },
    rp_title: { ko: 'Mode 3 서비스', en: 'Mode 3 Service' },
    rp_status_title: { ko: '서비스 상태', en: 'Service status' },
    rp_login_title: { ko: '로그인', en: 'Log in' },
    rp_login_desc: { ko: '지갑이 신원 기관의 서명과 영지식 증명으로 이 서비스 전용 주소를 만듭니다. 신원 기관은 어느 서비스인지 모릅니다.', en: 'The wallet derives a service-specific address from the authority’s signature and a zero-knowledge proof. The authority never learns which service.' },
    rp_session_title: { ko: '내 세션', en: 'My session' },
    rp_logins_title: { ko: '로그인 기록', en: 'Login records' },
    rp_open_title: { ko: '승인 개봉', en: 'Authorized opening' },
    rp_open_desc: { ko: '서비스와 신원 기관이 함께, 운영자 승인 아래에서만 사용자를 알아냅니다.', en: 'Only the service and the authority together, with operator approval, can identify the user.' },
    admin_title: { ko: 'Mode 3 신원 기관 관리자', en: 'Mode 3 Authority Admin' },
    admin_pending_rps: { ko: '승인 대기 서비스 {n}', en: '{n} services awaiting approval' },
    admin_pending_openings: { ko: '개봉 요청 {n}', en: '{n} opening requests' },
    admin_accounts_title: { ko: '계정', en: 'Accounts' }, admin_rps_title: { ko: '서비스', en: 'Services' }, admin_openings_title: { ko: '개봉 요청', en: 'Opening requests' }, admin_rcl_title: { ko: '폐기 목록', en: 'Revocation list' },
    account_title: { ko: 'Mode 3 내 계정', en: 'Mode 3 My Account' },
    account_revoke_title: { ko: '내 계정 폐기', en: 'Revoke my account' },
    account_revoke_desc: { ko: '기기를 잃었을 때 비밀번호만으로 계정을 폐기합니다. 지갑 키는 필요 없습니다.', en: 'Revoke your account with just the password, e.g. after losing a device. No wallet key needed.' },
    // 단계 힌트(안내 바 "다음" 문장의 {what})
    hint_approve: { ko: '등록된 서비스를 승인', en: 'approve the registered service' },
    hint_register: { ko: '지갑 등록', en: 'register the wallet' },
    hint_login: { ko: '로그인', en: 'log in' },
    hint_use: { ko: '재검증·세션 요청 또는 트랜잭션', en: 'revalidate, make a request, or send a transaction' },
    hint_disclose: { ko: '속성 조건을 골라 트랜잭션 또는 조건 요구 로그인', en: 'send a transaction with attribute conditions, or log in with a required predicate' },
    hint_revoke: { ko: '세션 하나 또는 계정 폐기 → 게시', en: 'revoke one session or the account → publish' },
    hint_open: { ko: '개봉 요청 → 관리자 승인 → 결과 확인', en: 'request opening → admin approves → read result' },
    // 서비스 페이지(rp.html) — 버튼·배지·한 줄 요약
    none: { ko: '(없음)', en: '(none)' },
    refresh: { ko: '새로고침', en: 'Refresh' },
    rp_login_btn: { ko: '로그인', en: 'Log in' },
    rp_reval_btn: { ko: '세션 재검증', en: 'Revalidate session' },
    rp_request_btn: { ko: '세션 요청 보내기', en: 'Send session request' },
    rp_open_req: { ko: '개봉 요청', en: 'Request opening' },
    rp_open_poll: { ko: '결과 확인', en: 'Check result' },
    rp_open_tx: { ko: '해시로 요청', en: 'Request by hash' },
    rp_open_tx_label: { ko: '트랜잭션 해시', en: 'Transaction hash' },
    rp_open_tx_note: { ko: '트랜잭션은 지갑 페이지에서 보냅니다(설계 2026-09-16 §6).', en: 'Transactions are sent from the wallet page (design 2026-09-16 §6).' },
    rp_pending_badge: { ko: '승인 대기', en: 'Awaiting approval' },
    rp_active_badge: { ko: '활성', en: 'Active' },
    rp_status_approved: { ko: '신원 기관의 승인을 받은 서비스입니다.', en: 'This service is approved by the identity authority.' },
    rp_status_pending: { ko: '신원 기관의 승인을 기다립니다. 관리자 페이지에서 승인하면 5초 안에 켜집니다.', en: 'Waiting for the identity authority to approve. Approve it on the admin page and this turns on within 5 s.' },
    rp_policy: { ko: '정책: 국가 ∈ {{countries}}, 나이 ≥ {minAge}', en: 'Policy: country ∈ {{countries}}, age ≥ {minAge}' },
    rp_no_attrgate: { ko: '속성 조건 컨트랙트가 없습니다(팩토리 미배포) — 조건 요구 로그인을 쓸 수 없습니다.', en: 'No attribute-condition contract (the factory is not deployed) — predicate logins are unavailable.' },
    rp_require_pred: { ko: '조건 요구(국가·나이)', en: 'Require predicate (country·age)' },
    rp_session_desc: { ko: '로그인 뒤에 활성화됩니다. 재검증은 이 세션이 아직 폐기되지 않았음을 다시 보입니다.', en: 'Enabled after login. Revalidation re-proves that this session has not been revoked.' },
    rp_logins_desc: { ko: '이 서비스에 남은 기록입니다. 서비스는 누구인지 모르고 이 주소만 압니다.', en: 'What this service recorded. It never learns who you are — only this address.' },
    rp_login_same_ppid: { ko: '새 세션. 이 서비스에서의 내 주소는 이전과 같습니다.', en: 'New session. Your address at this service is unchanged.' },
    rp_login_new_ppid: { ko: '새 세션. 이 서비스에서만 쓰는 주소를 받았습니다.', en: 'New session. You received an address used only at this service.' },
    rp_reval_cached: { ko: '캐시된 증명 재사용', en: 'Cached proof reused' },
    rp_reval_fresh: { ko: '새 폐기 목록으로 증명을 다시 만들었습니다.', en: 'A fresh proof was made against the new revocation list.' },
    rp_request_echo: { ko: '서비스가 세션 서명을 확인하고 “{echo}” 를 돌려줬습니다.', en: 'The service verified the session signature and echoed “{echo}”.' },
    rp_wallet_checking: { ko: '지갑 비밀 모드 확인 중…', en: 'Checking the wallet secret mode…' },
    rp_wallet_snap: { ko: '지갑 비밀=snap', en: 'Wallet secrets=snap' },
    rp_wallet_file: { ko: '지갑 비밀=file', en: 'Wallet secrets=file' },
    rp_wallet_snap_note: { ko: '로그인은 지갑 승인 팝업으로 갑니다 — 비밀은 MetaMask Snap 안에만 있습니다.', en: 'Login goes through the wallet approval popup — secrets stay inside the MetaMask Snap.' },
    rp_wallet_file_note: { ko: '로그인은 지갑 에이전트를 직접 부릅니다(비밀은 파일에 있습니다).', en: 'Login calls the wallet agent directly (secrets live in a file).' },
    rp_wallet_unknown: { ko: '지갑 설정 못 읽음', en: 'Wallet config unreadable' },
    rp_wallet_unknown_note: { ko: '지갑 설정({url})을 못 읽었습니다({err}) — 일단 file 모드로 봅니다. 지갑 에이전트가 떠 있는지 확인하세요. 지갑이 실제로 snap 모드라면 로그인이 CORS 로 막힙니다.', en: 'Could not read the wallet configuration ({url}): {err} — assuming file mode. Check that the wallet agent is running; if the wallet really is in snap mode, login will be blocked by CORS.' },
    rp_error_wallet_cfg: { ko: '지갑 설정(/wallet/config)을 못 읽어 비밀 모드를 모릅니다. 지갑 에이전트({origin})를 확인하세요.', en: 'The wallet secret mode is unknown because /wallet/config could not be read. Check the wallet agent ({origin}).' },
    rp_popup_blocked_hint: { ko: '이 사이트의 팝업을 허용한 뒤 다시 시도하세요.', en: 'Allow popups for this site, then try again.' },
    rp_popup_timeout: { ko: '승인 창이 제한 시간 안에 끝나지 않았습니다.', en: 'The approval window did not finish in time.' },
    rp_popup_closed: { ko: '승인 창이 결과 없이 닫혔습니다.', en: 'The approval window closed without a result.' },
    rp_reauth_unknown: { ko: '이 페이지는 이 세션의 AI 에이전트 허용 여부를 모릅니다(새로고침 등). 다시 로그인하세요.', en: 'This page does not know this session’s “allow AI agent” value (e.g. it was reloaded). Log in again.' },
    rp_disclosed: { ko: '공개한 조건: {what}', en: 'Disclosed conditions: {what}' },
    rp_disc_none: { ko: '공개 없음', en: 'None' },
    rp_disc_range: { ko: '{attr} {lo}–{hi}', en: '{attr} {lo}–{hi}' },
    rp_disc_set: { ko: '{attr} ∈ 허용 집합', en: '{attr} ∈ allowed set' },
    rp_col_time: { ko: '시각', en: 'Time' },
    rp_col_address: { ko: '이 서비스에서의 주소', en: 'Address at this service' },
    rp_col_disclosure: { ko: '공개한 조건', en: 'Disclosed conditions' },
    rp_col_agent: { ko: 'AI 에이전트', en: 'AI agent' },
    rp_col_rs: { ko: '세션 r_s', en: 'Session r_s' },
    rp_col_root: { ko: '폐기 목록 root', en: 'Revocation root' },
    rp_col_action: { ko: '작업', en: 'Action' },
    rp_agent_yes: { ko: '허용', en: 'Allowed' },
    rp_agent_no: { ko: '허용 안 함', en: 'Not allowed' },
    rp_no_logins: { ko: '아직 로그인 기록이 없습니다.', en: 'No login records yet.' },
    rp_open_requested_title: { ko: '개봉 요청 접수', en: 'Opening requested' },
    rp_open_requested: { ko: '개봉 요청을 보냈습니다. 신원 기관 관리자가 승인하면 “결과 확인”에서 볼 수 있습니다.', en: 'The opening request was sent. Once the authority admin approves it, press “Check result”.' },
    rp_open_awaiting: { ko: '관리자 승인 대기 중', en: 'Awaiting admin approval' },
    rp_open_result_title: { ko: '개봉 결과', en: 'Opening result' },
    rp_open_result: { ko: '신원 기관이 알아낸 사용자: uid={uid}, AI 에이전트 {agent}', en: 'The authority identified the user: uid={uid}, AI agent {agent}' },
    rp_open_failed: { ko: '개봉 요청 실패', en: 'Opening request failed' },
  },
  terms: {
    PPID: { ko: '이 서비스에서의 내 주소', en: 'My address at this service', expert: 'PPID = Poseidon(uid, s_u, chainid, arid)' },
    AA: { ko: '신원 기관', en: 'Identity authority', expert: 'AA / CIA, pk_CIA' },
    session: { ko: '로그인 세션', en: 'Login session', expert: 'r_s, pk_i, max_height' },
    root: { ko: '폐기 목록 버전', en: 'Revocation list version', expert: 'root, epoch, age(blocks)' },
    proof: { ko: '영지식 증명', en: 'Zero-knowledge proof', expert: 'π_rp (Groth16), prove ms, cache hit' },
    disclosure: { ko: '공개할 속성 조건', en: 'Attribute conditions to reveal', expert: 'disc_mask, lo[4], hi[4], set_sel, set_root' },
    cred: { ko: '내 자격증명', en: 'My credential', expert: 'C_u → Cf_u; session ticket C_s → Cf_s' },
    tag: { ko: '추적용 봉인', en: 'Sealed trace', expert: 'tag = (c1, c2) under pk_trace' },
    allowAgent: { ko: 'AI 에이전트 허용', en: 'Allow AI agent', expert: 'allowAgent ∈ {0,1}' },
    attr0: { ko: '출생연도', en: 'Birth year', expert: 'attrs[0] (a₁), 64-bit' },
    attr1: { ko: '국가', en: 'Country', expert: 'attrs[1] (a₂), ISO 3166 numeric' },
    attr2: { ko: '등급', en: 'Tier', expert: 'attrs[2] (a₃)' },
    attr3: { ko: '예비', en: 'Spare', expert: 'attrs[3] (a₄)' },
  },
  steps: [
    { key: 'approve', where: ['admin'], ko: { title: '서비스 승인', hint: '신원 기관 운영자가 서비스 등록을 승인합니다.' }, en: { title: 'Approve service', hint: 'The authority operator approves the service registration.' } },
    { key: 'register', where: ['wallet'], ko: { title: '지갑 등록', hint: '지갑이 신원 기관에 한 번 등록하고 자격증명을 받습니다.' }, en: { title: 'Register wallet', hint: 'The wallet registers once and receives a credential.' } },
    { key: 'login', where: ['rp'], ko: { title: '로그인', hint: '서비스 전용 주소로 로그인합니다.' }, en: { title: 'Log in', hint: 'Log in with a service-specific address.' } },
    { key: 'use', where: ['rp', 'wallet'], ko: { title: '이용', hint: '세션을 재검증하거나 요청·트랜잭션을 보냅니다.' }, en: { title: 'Use', hint: 'Revalidate the session, make a request, or send a transaction.' } },
    { key: 'disclose', where: ['wallet', 'rp'], ko: { title: '공개·조건', hint: '속성 조건만 골라 공개합니다.' }, en: { title: 'Disclose', hint: 'Reveal only chosen attribute conditions.' } },
    { key: 'revoke', where: ['wallet', 'account', 'admin'], ko: { title: '폐기·복구', hint: '세션 하나 또는 계정을 폐기하고 게시합니다.' }, en: { title: 'Revoke & recover', hint: 'Revoke one session or the account, then publish.' } },
    { key: 'open', where: ['rp', 'admin'], ko: { title: '승인 개봉', hint: '서비스와 기관이 함께 사용자를 알아냅니다.' }, en: { title: 'Authorized opening', hint: 'Service and authority identify the user together.' } },
  ],
  verdicts: {
    login_ok: { ko: '로그인 성공', en: 'Login succeeded' },
    registered: { ko: '등록됨', en: 'Registered' },
    tx_ok: { ko: '전송 성공', en: 'Sent' },
    reval_ok: { ko: '재검증 성공', en: 'Revalidated' },
    reauth_denied: { ko: '재승인 불가', en: 'Re-approval not possible' },
    popup_blocked: { ko: '팝업이 차단됐다', en: 'Popup was blocked' },
    request_ok: { ko: '세션 요청 성공', en: 'Request accepted' },
    request_failed: { ko: '세션 요청 실패', en: 'Request failed' },
    revoked_ok: { ko: '폐기 요청 접수', en: 'Revocation accepted' },
    login_failed: { ko: '로그인 실패', en: 'Login failed' },
    reval_failed: { ko: '재검증 실패', en: 'Revalidation failed' },
    tx_failed: { ko: '전송 실패', en: 'Send failed' },
  },
  reasons: {
    // where: 'rp' | 'wallet' | 'page' | 'aa'. 각 항목의 cause·action 은 그 코드를 내는 소스의 실제 조건을 보고 썼다
    // (lib/mode3_rp.js verifyLogin, mode3_rp.js 세션 라우트, mode3_wallet_agent.js, lib/mode3_onchain.js, cia.js, mode3/wallet.html).
    stale_root: { where: 'rp', ko: { title: '폐기 목록이 오래됐습니다', cause: '지갑이 최신 폐기 목록으로 증명하지 않았습니다.', action: '"동기화 생략"을 끄고 다시 재검증하세요.' }, en: { title: 'Revocation list is stale', cause: 'The wallet did not prove against the latest revocation list.', action: 'Turn off "skip sync" and revalidate again.' } },
    root_too_old: { where: 'rp', ko: { title: '폐기 목록이 너무 오래 게시되지 않았습니다', cause: '마지막 게시 이후 지난 블록 수가 허용 한도(maxRootAge)를 넘었습니다 — 신원 기관의 게시가 멈춘 것입니다.', action: '신원 기관을 살리고 관리자 페이지에서 폐기 목록을 게시한 뒤 다시 시도하세요.' }, en: { title: 'Revocation list has not been published recently enough', cause: 'More blocks have passed since the last publication than the limit (maxRootAge) allows — the authority stopped publishing.', action: 'Bring the authority back up, publish the revocation list from the admin page, then try again.' } },
    revalidate_required: { where: 'rp', ko: { title: '세션을 다시 검증해야 합니다', cause: '이 세션을 만든 뒤 폐기 목록이 새로 게시돼 버전이 달라졌습니다.', action: '"세션 재검증"을 먼저 누른 뒤 요청을 다시 보내세요.' }, en: { title: 'The session must be revalidated', cause: 'A new revocation list was published after this session was created, so the versions differ.', action: 'Press "revalidate session" first, then send the request again.' } },
    predicate_unmet: { where: 'rp', ko: { title: '요구한 조건을 만족하지 못했습니다', cause: '로그인 자체는 유효하지만 서비스가 요구한 조건(허용 국가 집합 소속 또는 최소 나이)이 공개된 값으로 충족되지 않았습니다.', action: '그 조건을 공개하도록 지갑에서 다시 로그인하거나, 로그인 화면에서 요구 조건을 끄세요.' }, en: { title: 'The required condition was not met', cause: 'The login itself is valid, but the disclosed values do not satisfy the condition the service required (membership in the allowed country set, or a minimum age).', action: 'Log in again disclosing that condition, or turn the requirement off on the login form.' } },
    factory_constants_unavailable: { where: 'rp', ko: { title: '서비스가 체인 설정을 읽지 못했습니다', cause: '서비스가 팩토리 컨트랙트에서 maxRootAge·maxLifetime 을 읽지 못해 검증을 멈췄습니다(몇 초마다 다시 시도합니다).', action: '체인 노드가 떠 있는지 확인하고, 체인을 새로 띄웠다면 서비스 등록 파일의 팩토리 주소를 지우고 서비스를 재시작하세요.' }, en: { title: 'The service could not read its chain settings', cause: 'The service could not read maxRootAge/maxLifetime from the factory contract and stopped verifying (it retries every few seconds).', action: 'Check that the chain node is up; if the chain was restarted, clear the factory address in the service registration file and restart the service.' } },
    registration_pending: { where: 'rp', ko: { title: '서비스가 아직 승인되지 않았습니다', cause: '신원 기관이 이 서비스의 등록을 아직 승인하지 않아 검증기가 없습니다.', action: '신원 기관 관리자 페이지에서 이 서비스를 승인하세요.' }, en: { title: 'The service is not approved yet', cause: 'The authority has not approved this service’s registration, so no verifier exists.', action: 'Approve this service on the authority admin page.' } },
    bad_signature: { where: 'rp', ko: { title: '서명이 맞지 않습니다', cause: '요청에 붙은 서명이 그 세션의 키(pk_i)로 만든 것이 아닙니다.', action: '서비스에서 다시 로그인해 새 세션을 만드세요.' }, en: { title: 'The signature does not match', cause: 'The signature on the request was not made with that session’s key (pk_i).', action: 'Log in again at the service to create a new session.' } },
    bad_rp_cert: { where: 'wallet', ko: { title: '서비스 인증서를 믿을 수 없습니다', cause: '서비스가 준 인증서가 신원 기관의 서명이 아니거나, 요청을 보낸 오리진이 인증서에 적힌 오리진과 다릅니다.', action: '승인된 서비스의 원래 주소에서 다시 시도하세요.' }, en: { title: 'The service certificate cannot be trusted', cause: 'The certificate the service presented is not signed by the authority, or the requesting origin differs from the origin in the certificate.', action: 'Try again from the approved service’s own address.' } },
    bad_proof: { where: 'rp', ko: { title: '영지식 증명이 검증되지 않았습니다', cause: '지갑이 보낸 증명이 서비스의 검증 키로 검증되지 않았습니다.', action: '지갑과 서비스가 같은 회로 빌드를 쓰는지 확인하고 다시 로그인하세요.' }, en: { title: 'The zero-knowledge proof did not verify', cause: 'The proof sent by the wallet did not verify under the service’s verification key.', action: 'Check that the wallet and the service use the same circuit build, then log in again.' } },
    expired: { where: 'rp', ko: { title: '세션이 만료됐습니다', cause: '체인의 현재 블록 높이가 이 세션의 만료 높이(max_height)를 넘었습니다.', action: '서비스에서 다시 로그인하세요.' }, en: { title: 'The session has expired', cause: 'The chain’s current block height is past this session’s expiry height (max_height).', action: 'Log in again at the service.' } },
    malformed: { where: 'rp', ko: { title: '요청 형식이 잘못됐습니다', cause: '요청 본문의 증명·공개 입력·서명·세션 값의 형식이 서버가 기대한 것과 다릅니다.', action: '페이지를 새로고침하고 다시 시도하세요.' }, en: { title: 'The request is malformed', cause: 'The proof, public signals, signature or session value in the request body do not have the shape the server expects.', action: 'Reload the page and try again.' } },
    revoked: { where: 'wallet', ko: { title: '자격증명을 더 쓸 수 없습니다', cause: '이 계정의 자격증명 리프가 폐기 목록에 게시됐거나, 신원 기관에서 자격증명이 다른 것으로 바뀌었습니다(속성 변경 등) — 이 지갑의 기존 세션이 모두 죽습니다.', action: '서비스에서 다시 로그인하세요 — 지갑이 새 자격증명을 받습니다.' }, en: { title: 'The credential can no longer be used', cause: 'This account’s credential leaf was published on the revocation list, or the authority replaced the credential with a different one (e.g. an attribute change) — every existing session of this wallet dies.', action: 'Log in again at the service — the wallet will receive a fresh credential.' } },
    revoked_session: { where: 'wallet', ko: { title: '이 세션은 폐기됐습니다', cause: '이 로그인 세션만 폐기 목록에 올라 게시됐습니다. 다른 세션과 계정은 그대로입니다.', action: '서비스에서 다시 로그인하세요.' }, en: { title: 'This session was revoked', cause: 'Only this login session was published on the revocation list. Other sessions and the account are intact.', action: 'Log in again at the service.' } },
    account_disabled: { where: 'wallet', ko: { title: '계정이 폐기돼 있습니다', cause: '신원 기관에서 이 계정이 폐기돼 새 세션을 발급하지 않습니다.', action: '신원 기관 관리자에게 계정 상태를 문의하세요.' }, en: { title: 'The account is disabled', cause: 'The authority has revoked this account and will not issue new sessions.', action: 'Ask the authority admin about the account’s status.' } },
    needs_consent: { where: 'wallet', ko: { title: '다시 승인해야 합니다', cause: '지갑 에이전트가 재시작해 이 세션의 메모리 증인이 사라졌습니다 — 서명할 비밀이 없습니다.', action: '서비스에서 이 세션을 한 번 재검증해 재승인 창을 거친 뒤 다시 시도하세요.' }, en: { title: 'Re-approval is needed', cause: 'The wallet agent restarted and this session’s in-memory witness is gone — there is no secret left to sign with.', action: 'Revalidate this session once at the service to go through the re-approval popup, then try again.' } },
    bad_factory: { where: 'wallet', ko: { title: '팩토리 컨트랙트를 믿을 수 없습니다', cause: '서비스가 준 팩토리 주소의 온체인 값이 인증서·신원 기관 키·로그 주소와 다르거나, 팩토리·검증자 코드가 지갑의 참조 빌드와 다릅니다.', action: '서비스가 올바른 팩토리를 쓰는지 확인하고, 컨트랙트를 바꿨다면 지갑 쪽에서 먼저 컴파일(npx hardhat compile)하세요.' }, en: { title: 'The factory contract cannot be trusted', cause: 'The on-chain values at the factory address the service gave differ from the certificate, authority key or log address, or its factory/verifier code differs from the wallet’s reference build.', action: 'Check that the service points at the right factory; if you changed the contracts, compile first on the wallet side (npx hardhat compile).' } },
    no_code: { where: 'wallet', ko: { title: '팩토리 주소에 컨트랙트가 없습니다', cause: '서비스가 준 팩토리 주소에 온체인 코드가 없습니다 — 체인을 새로 띄웠는데 옛 주소를 쓰고 있을 때 납니다.', action: '서비스 등록 파일의 팩토리 주소를 지우고 서비스를 재시작해 새로 배포하게 하세요.' }, en: { title: 'There is no contract at the factory address', cause: 'The factory address the service gave has no on-chain code — typical after restarting the chain while an old address is still configured.', action: 'Clear the factory address in the service registration file and restart the service so it deploys a new one.' } },
    factory_code_mismatch: { where: 'wallet', ko: { title: '팩토리 코드가 참조 빌드와 다릅니다', cause: '팩토리의 온체인 코드 해시가 지갑이 가진 참조 빌드(artifacts/)의 해시와 다릅니다.', action: '컨트랙트를 바꿨다면 npx hardhat compile 로 참조 빌드를 맞추고, 아니라면 그 팩토리를 쓰지 마세요.' }, en: { title: 'The factory code differs from the reference build', cause: 'The factory’s on-chain code hash differs from the wallet’s reference build (artifacts/).', action: 'If you changed the contracts, run npx hardhat compile to refresh the reference build; otherwise do not use that factory.' } },
    verifier_code_mismatch: { where: 'wallet', ko: { title: '증명 검증자 코드가 참조 빌드와 다릅니다', cause: '팩토리가 가리키는 검증자의 온체인 코드가 참조 빌드와 다릅니다 — 무엇이든 통과시키는 가짜 검증자일 수 있습니다.', action: '컨트랙트를 바꿨다면 npx hardhat compile 로 참조 빌드를 맞추고, 아니라면 그 팩토리를 쓰지 마세요.' }, en: { title: 'The verifier code differs from the reference build', cause: 'The on-chain code of the verifier the factory points at differs from the reference build — it could be a fake verifier that accepts anything.', action: 'If you changed the contracts, run npx hardhat compile to refresh the reference build; otherwise do not use that factory.' } },
    allow_agent_mismatch: { where: 'wallet', ko: { title: 'AI 에이전트 허용 값이 다릅니다', cause: '재승인 창이 동의 창에 쓴 "AI 에이전트 허용" 값이 그 세션의 실제 값과 다릅니다.', action: '서비스에서 재검증을 다시 시작해 그 세션의 값 그대로 승인하세요.' }, en: { title: 'The "allow AI agent" value does not match', cause: 'The "allow AI agent" value the re-approval popup showed in the consent dialog differs from that session’s actual value.', action: 'Start the revalidation again at the service and approve with that session’s own value.' } },
    no_session: { where: 'wallet', ko: { title: '그 세션을 지갑이 들고 있지 않습니다', cause: '이미 폐기했거나 만료돼 지갑에서 사라진 세션입니다(서비스가 지정한 서비스 식별자와 다를 때도 납니다).', action: '서비스에서 다시 로그인하세요.' }, en: { title: 'The wallet does not hold that session', cause: 'The session is gone from the wallet because it was already revoked or expired (this also occurs when the service identifier does not match).', action: 'Log in again at the service.' } },
    not_registered: { where: 'wallet', ko: { title: '지갑이 등록되지 않았습니다', cause: '이 지갑 에이전트에 신원 기관 등록이 없습니다.', action: '지갑 페이지의 "내 신원"에서 먼저 등록하세요.' }, en: { title: 'The wallet is not registered', cause: 'This wallet agent has no registration with the authority.', action: 'Register first under "My identity" on the wallet page.' } },
    cia_unavailable: { where: 'wallet', ko: { title: '신원 기관에 연결하지 못했습니다', cause: '지갑이 신원 기관 서버를 부르지 못했습니다 — 꺼져 있거나 주소가 다릅니다.', action: '신원 기관 서버(:4100)가 떠 있는지 확인하고 다시 시도하세요.' }, en: { title: 'Could not reach the identity authority', cause: 'The wallet failed to call the authority server — it is down or configured at a different address.', action: 'Check that the authority server (:4100) is running and try again.' } },
    witness_required: { where: 'wallet', ko: { title: 'Snap 동의가 빠졌습니다', cause: 'Snap 모드에서는 요청에 Snap 이 만든 증인이 함께 와야 하는데 오지 않았습니다.', action: '지갑 승인 창에서 Snap 동의를 마친 뒤 다시 시도하세요.' }, en: { title: 'The Snap consent is missing', cause: 'In Snap mode the request must carry a witness produced by the Snap, and none arrived.', action: 'Complete the Snap consent in the wallet approval window, then try again.' } },
    internal: { where: 'wallet', ko: { title: '서버에서 예상치 못한 오류가 났습니다', cause: '요청을 처리하던 중 서버가 예상하지 못한 오류를 냈습니다 — 원문은 "자세히"에 있습니다.', action: '"자세히"의 내용과 서버 로그를 확인하세요.' }, en: { title: 'The server hit an unexpected error', cause: 'The server threw an error it did not expect while handling the request — the original message is under "Details".', action: 'Check the message under "Details" and the server log.' } },
    user_denied: { where: 'page', ko: { title: '승인 창에서 거절했습니다', cause: '지갑 승인 창이나 MetaMask 에서 요청을 거절했습니다.', action: '다시 시도해 승인 창에서 승인을 누르세요.' }, en: { title: 'The request was denied in the approval window', cause: 'You rejected the request in the wallet approval window or in MetaMask.', action: 'Try again and approve in the window.' } },
    snap_unavailable: { where: 'page', ko: { title: 'MetaMask Snap 을 쓸 수 없습니다', cause: 'MetaMask 확장이 없거나(window.ethereum 없음) Snap 호출이 실패했습니다.', action: 'MetaMask 를 설치·잠금 해제하고 지갑 페이지에서 Snap 을 연결하세요.' }, en: { title: 'The MetaMask Snap is unavailable', cause: 'The MetaMask extension is missing (no window.ethereum) or the Snap call failed.', action: 'Install and unlock MetaMask, then connect the Snap on the wallet page.' } },
    wallet_error: { where: 'page', ko: { title: 'MetaMask 작업이 실패했습니다', cause: 'MetaMask 가 사용자 거절이 아닌 오류를 냈습니다 — 원문은 "자세히"에 있습니다.', action: 'MetaMask 의 연결된 계정과 네트워크를 확인하고 다시 시도하세요.' }, en: { title: 'The MetaMask operation failed', cause: 'MetaMask returned an error that was not a user rejection — the original message is under "Details".', action: 'Check the connected account and network in MetaMask, then try again.' } },
    unknown_session: { where: 'aa', ko: { title: '신원 기관에 그 세션 기록이 없습니다', cause: '폐기하려는 세션이 이 계정의 기록에 없습니다 — 세션 기록을 남기기 전에 발급됐거나 만료 정리로 사라졌습니다.', action: '그 세션은 만료로만 끝납니다 — 새로 로그인한 세션에서 다시 시도하세요.' }, en: { title: 'The authority has no record of that session', cause: 'The session you are revoking is not in this account’s records — it was issued before session records existed, or was cleaned up after expiry.', action: 'That session can only end by expiry — try again with a freshly created session.' } },
    no_user_cred: { where: 'aa', ko: { title: '이 자격증명은 더 이상 유효하지 않습니다', cause: '지갑이 들고 있는 자격증명이 신원 기관에서 이미 물려(retire) 활성 자격증명이 아닙니다 — 발급을 처리하는 사이에 계정이 폐기되거나 자격증명이 바뀐 경우에도 같습니다.', action: '지갑에서 다시 로그인하면 새 자격증명을 받습니다.' }, en: { title: 'This credential is no longer active', cause: 'The credential the wallet holds has been retired at the authority and is not the active one — this also covers the account being disabled or the credential changing while issuance was in flight.', action: 'Log in again from the wallet to receive a fresh credential.' } },
    user_cred_retired: { where: 'wallet', ko: { title: '새 자격증명을 받지 못했습니다', cause: '신원 기관에서 자격증명이 이미 물렸고 지갑이 새로 받는 것도 실패했습니다(연속 폐기·경합).', action: '잠시 뒤 다시 로그인하세요.' }, en: { title: 'Could not obtain a fresh credential', cause: 'The credential was already retired at the authority and the wallet’s retry to obtain a new one also failed (back-to-back revocation or a race).', action: 'Log in again in a moment.' } },
  },
};
